[package]
name = "tinyvm"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
build = "build.rs"

[build-dependencies]
cc = "1.0.47"
